base_url = "https://blog.thibaut-rousseau.com"
build_search_index = true
generate_feeds = true
title = "Thibaut Rousseau's Blog"
author = "Thibaut Rousseau"
taxonomies = [
  { name = "tags", render = false }
]

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["syntaxes"]
