base_url = "https://blog.thibaut-rousseau.com"
build_search_index = true
generate_feeds = true
title = "Thibaut Rousseau's Blog"
author = "Thibaut Rousseau"
taxonomies = [{ name = "tags", render = false }]


[markdown.highlighting]
theme = "tokyo-night"
error_on_missing_language = true
